version: '3.9'
services:
  database:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .database.env
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
