version: '3.9'
services:
  web:
    container_name: next
    image: node:18-alpine
    command: ./run.app.sh
    working_dir: /apps/app
    depends_on:
      - database
    ports:
      - 3000:3000
      - 4444:4444
    volumes:
      - .:/apps/app
    env_file:
      - .env
  database:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .database.env
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local
